### ISSUE TITLE
using Clean text on a column of a dataframe

### ISSUE THREAD

**Issue by hunaidkhan2000** [prasanthg3/cleantext#1]
Hi I am trying to use your awesome package on a dataframe column but it is not providing me any answer i have tried using apply and creating a fuction also 

## my function #####
```
import cleantext
def clean_text(text):
  cleantext.clean(text,
                  all= False, # Execute all cleaning operations
                  extra_spaces=True ,  # Remove extra white space 
                  stemming=True , # Stem the words
                  stopwords=True ,# Remove stop words
                  lowercase=True ,# Convert to lowercase
                  numbers=False ,# Remove all digits 
                  punct=True ,# Remove all punctuations
                  stp_lang='english'  # Language for stop words
                  )
  return (text)
```

```
### applying the function #####
df1['text'] = df1['text'].apply(clean_text)
and 
df1['text'] = clean_text(df1['text'] )
```

Please let me know how to work with data frames using the library

**Comment by prasanthg3** [comment]
Hi, 
Looks like you are returning input text in your function, but not the cleaned text. it should return the output from cleantext.clean function.
To use in the dataframes, you can simply follow the below approach,

``` df['text']=df['text'].apply(lambda x: cleantext.clean(x, all=True) ```


You can also use specific parameters instead of all=True according to your requirement.

**Comment by hunaidkhan2000** [comment]
Hey Thanks it worked like a charm. Thanks for creating this awesome package
