### ISSUE TITLE
Returning sampl instead of sample

### ISSUE THREAD

**Issue by AfsalInovicsTech** [prasanthg3/cleantext#10]
Recently i have used this package for learning purpose.
When we are using clean_words method i got sampl instead of sample.

**Comment by prasanthg3** [comment]
Could you add the parameters used for `clean_words` method? If clean_all or stemming is enabled, it stems the word sample/samples to sampl.

**Comment by AfsalInovicsTech** [comment]
@prasanthg3 Thanks i got it if i am setting that it is working
