### ISSUE TITLE
no attribute named clean

### ISSUE THREAD

**Issue by deepcode-debug** [prasanthg3/cleantext#2]
I believe you guys have changed the module structure in that case the documentation should also be updated
I am getting the below error:

AttributeError: module 'cleantext' has no attribute 'clean'

by using the method cleantext.clean(text)

**Comment by prasanthg3** [comment]
Could you provide more details for the error? Did you install cleantext using pip or pull through git?

**Comment by deepcode-debug** [comment]
I have installed using pip. Could solve it using clean.clean

**Comment by prasanthg3** [comment]
I am unable to reproduce this error. I suggest to use version 1.1.3.

**Comment by miovee** [comment]
im having samiler problem

 `for text1 in  i.text.split():
        print (text1)
#%%     
        name= cleantext.clean_words(text1, extra_spaces=True,  # Remove extra white space 
                                    stopwords=True ,# Remove stop words
                                    lowercase=True ,# Convert to lowercase
                                    numbers=True ,# Remove all digits 
                                    punct=True ,# Remove all punctuations
                                    stp_lang='english'  # Language for stop words
                                    )    
        print (name.strip())
        brand.append (name.strip())`

return >>
----> 1 name= cleantext.clean_words(text1, extra_spaces=True,  # Remove extra white space 
      2                             stopwords=True ,# Remove stop words
      3                             lowercase=True ,# Convert to lowercase
      4                             numbers=True ,# Remove all digits
      5                             punct=True ,# Remove all punctuations

**AttributeError: module 'cleantext' has no attribute 'clean_words'**
