### ISSUE TITLE
TypeError: clean() got an unexpected keyword argument 'all'

### ISSUE THREAD

**Issue by mingjun1120** [prasanthg3/cleantext#3]
`cleantext.clean()` cannot work in **Jupyter Notebook** but it works well in other notebooks such as **Deepnote**.

**Jupyter Notebook:**
![image](https://user-images.githubusercontent.com/54136320/125183945-c1198880-e24c-11eb-8556-d8d6c64165de.png)

**Comment by ShubhamRaiGit** [comment]
@mingjun1120 instead of passing all keyword try passing clean_all as keyword
`df['review'].apply(cleantext.clean, clean_all=True)`
